### ISSUE TITLE
RFC: Documentation TODO List

### ISSUE THREAD

**Issue by saterus** [Tahi-project/tahi#1826]
Lately I've been thinking about how we increase knowledge transfer among team members. We have a fairly large team spread across several time zones and countries. There's simply a lot of work being done and not everything is adequately explained to everyone _from a technical perspective_. I know I'm as guilty of this as anyone.

I'd like to solicit other opinions on what [documentation](http://stevelosh.com/blog/2013/09/teach-dont-tell/) would be helpful to have. I've started this out with a couple of ideas, but want to hear what other people think. I'm going to try and write up some of the things I am able to explain.
- [x] Our git workflow #1816 
- [x] Deploy Instructions for `release-candidate`, `lean`, and (future) `production`
- [ ] How to use the `Notifier`/`Subscription` sub-system
- [ ] How do `NestedQuestion`s work?
- [ ] What is `ihat` and how does it work?
- [ ] ...
- [ ] ...
- [ ] ...

**Please comment below**. I will edit this issue and add more to this list.
